"""Default advanced EEG figure gallery helpers."""

from .erp_gallery import MODULE as ERP_MODULE, FIGURE_FAMILIES as ERP_FIGURE_FAMILIES
from .erpimage_gallery import MODULE as ERPIMAGE_MODULE, FIGURE_FAMILIES as ERPIMAGE_FIGURE_FAMILIES
from .ica_gallery import MODULE as ICA_MODULE, FIGURE_FAMILIES as ICA_FIGURE_FAMILIES
from .resting_gallery import MODULE as RESTING_MODULE, FIGURE_FAMILIES as RESTING_FIGURE_FAMILIES
from .source_gallery import MODULE as SOURCE_MODULE, FIGURE_FAMILIES as SOURCE_FIGURE_FAMILIES
from .study_gallery import MODULE as STUDY_MODULE, FIGURE_FAMILIES as STUDY_FIGURE_FAMILIES
from .timefreq_gallery import MODULE as TIMEFREQ_MODULE, FIGURE_FAMILIES as TIMEFREQ_FIGURE_FAMILIES
from .connectivity_gallery import (
    MODULE as CONNECTIVITY_MODULE,
    FIGURE_FAMILIES as CONNECTIVITY_FIGURE_FAMILIES,
)

ALL_MODULES = [
    ERP_MODULE,
    ERPIMAGE_MODULE,
    RESTING_MODULE,
    TIMEFREQ_MODULE,
    ICA_MODULE,
    CONNECTIVITY_MODULE,
    SOURCE_MODULE,
    STUDY_MODULE,
]
